kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      pod-infra-container-image: gotok8s/pause:3.2
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  imageRepository: gotok8s
nodes:
- role: control-plane
  image: kindest/node:v1.19.1
- role: worker
  image: kindest/node:v1.19.1
- role: worker
  image: kindest/node:v1.19.1
