apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello
  annotations:
    nginx.ingress.kubernetes.io/proxy-set-header: "X-Request-ID $request_id"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      access_by_lua_file /etc/nginx/lua-scripts/signature.lua;
spec:
  ingressClassName: nginx
  rules:
    - host: hello.k8s.orb.local
      http:
        paths:
          - backend:
              service:
                name: hello
                port:
                  number: 8080
            path: /
            pathType: Prefix
