controller:
  config:
    allow-snippet-annotations: true
    enable-opentelemetry: "true"
    opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
    otlp-collector-host: "10.2.145.191"
    otlp-collector-port: "4317"
    otel-service-name: "ingress-nginx"
    otel-sampler: "AlwaysOn"
    otel-sampler-ratio: "1.0"
  opentelemetry:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        prometheus.io/path: "/metrics"
  extraVolumes:
    - name: lua-scripts
      configMap:
        name: lua-scripts
  extraVolumeMounts:
    - name: lua-scripts
      mountPath: /etc/nginx/lua-scripts
