apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: nginx
  rules:
    - host: test.example.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: my-nginx
                port:
                  number: 80
            path: /
